//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DischargerV2.Languages.Strings {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DischargerV2.Languages.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Channel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   COM Port과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Comport {
            get {
                return ResourceManager.GetString("Comport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current (C)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CurrMax (A)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CurrMax {
            get {
                return ResourceManager.GetString("CurrMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CurrMin (A)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CurrMin {
            get {
                return ResourceManager.GetString("CurrMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CurrSpec(A)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CurrSpec {
            get {
                return ResourceManager.GetString("CurrSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Discharger과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Discharger {
            get {
                return ResourceManager.GetString("Discharger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Discharger Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DischargerName {
            get {
                return ResourceManager.GetString("DischargerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Enter_Id {
            get {
                return ResourceManager.GetString("Enter_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter IP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Enter_Ip {
            get {
                return ResourceManager.GetString("Enter_Ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Enter_Name {
            get {
                return ResourceManager.GetString("Enter_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Enter_Password {
            get {
                return ResourceManager.GetString("Enter_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Ip {
            get {
                return ResourceManager.GetString("Ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log In과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Log_In {
            get {
                return ResourceManager.GetString("Log_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Model과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Module Channel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ModuleChannel {
            get {
                return ResourceManager.GetString("ModuleChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Progress Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ProgressTime {
            get {
                return ResourceManager.GetString("ProgressTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reconnect과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Reconnect {
            get {
                return ResourceManager.GetString("Reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Short Available과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ShortAvailable {
            get {
                return ResourceManager.GetString("ShortAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temperature (℃)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Temp {
            get {
                return ResourceManager.GetString("Temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temp Channel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TempChannel {
            get {
                return ResourceManager.GetString("TempChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TempMax (℃)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TempMax {
            get {
                return ResourceManager.GetString("TempMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TempMin (℃)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TempMin {
            get {
                return ResourceManager.GetString("TempMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temperature Module과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TempModule {
            get {
                return ResourceManager.GetString("TempModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Voltage (V)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Voltage {
            get {
                return ResourceManager.GetString("Voltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VoltMax (V)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string VoltMax {
            get {
                return ResourceManager.GetString("VoltMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VoltMin (V)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string VoltMin {
            get {
                return ResourceManager.GetString("VoltMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VoltSpec(V)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string VoltSpec {
            get {
                return ResourceManager.GetString("VoltSpec", resourceCulture);
            }
        }
    }
}
