//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DischargerV2.Languages.Strings {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DischargerV2.Languages.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   0V Discharge과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _0vDischarge {
            get {
                return ResourceManager.GetString("0vDischarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add New Device과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AddNewDevice {
            get {
                return ResourceManager.GetString("AddNewDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add New Model과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AddNewModel {
            get {
                return ResourceManager.GetString("AddNewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add New User과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AddNewUser {
            get {
                return ResourceManager.GetString("AddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Step과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AddStep {
            get {
                return ResourceManager.GetString("AddStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Admin과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Channel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AllChannel {
            get {
                return ResourceManager.GetString("AllChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Battery Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BatteryType {
            get {
                return ResourceManager.GetString("BatteryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Capacity (Ah)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Capacity {
            get {
                return ResourceManager.GetString("Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Capacity (Ah) [Optional]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CapacityOptional {
            get {
                return ResourceManager.GetString("CapacityOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Channel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   COM Port과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Comport {
            get {
                return ResourceManager.GetString("Comport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm New Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connected Channel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ConnectedChannel {
            get {
                return ResourceManager.GetString("ConnectedChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   C-Rate과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CRate {
            get {
                return ResourceManager.GetString("CRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create New User과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CreateNewUser {
            get {
                return ResourceManager.GetString("CreateNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current (A)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Current_NoUnits {
            get {
                return ResourceManager.GetString("Current_NoUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current SoC (%)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CurrentSoc {
            get {
                return ResourceManager.GetString("CurrentSoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CurrMax (A)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CurrMax {
            get {
                return ResourceManager.GetString("CurrMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CurrMin (A)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CurrMin {
            get {
                return ResourceManager.GetString("CurrMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CurrSpec(A)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CurrSpec {
            get {
                return ResourceManager.GetString("CurrSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device Register과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DeviceRegister {
            get {
                return ResourceManager.GetString("DeviceRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Discharger과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Discharger {
            get {
                return ResourceManager.GetString("Discharger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Discharger Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DischargerName {
            get {
                return ResourceManager.GetString("DischargerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Discharge Target과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DischargeTarget {
            get {
                return ResourceManager.GetString("DischargeTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter Current Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EnterCurrentPassword {
            get {
                return ResourceManager.GetString("EnterCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EnterId {
            get {
                return ResourceManager.GetString("EnterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter IP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EnterIp {
            get {
                return ResourceManager.GetString("EnterIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter New Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EnterNewPassword {
            get {
                return ResourceManager.GetString("EnterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter User Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EnterUserName {
            get {
                return ResourceManager.GetString("EnterUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fault Channel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FaultChannel {
            get {
                return ResourceManager.GetString("FaultChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finish과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Full Discharge과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FullDischarge {
            get {
                return ResourceManager.GetString("FullDischarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input Voltage and Capacity과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InputVoltageNCapacity {
            get {
                return ResourceManager.GetString("InputVoltageNCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Ip {
            get {
                return ResourceManager.GetString("Ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log In과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log-out과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mode과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Model과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Model Register과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ModelRegister {
            get {
                return ResourceManager.GetString("ModelRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Module Channel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ModuleChannel {
            get {
                return ResourceManager.GetString("ModuleChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monitor Values과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MonitorValues {
            get {
                return ResourceManager.GetString("MonitorValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Data과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nominal Voltage (V)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NominalVoltage {
            get {
                return ResourceManager.GetString("NominalVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pause과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the LogFileName과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PleaseEnterLogFileName {
            get {
                return ResourceManager.GetString("PleaseEnterLogFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cause과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PopupError_Comment_Cause {
            get {
                return ResourceManager.GetString("PopupError_Comment_Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PopupError_Comment_Description {
            get {
                return ResourceManager.GetString("PopupError_Comment_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error Code과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PopupError_Comment_ErrorCode {
            get {
                return ResourceManager.GetString("PopupError_Comment_ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Solution과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PopupError_Comment_Solution {
            get {
                return ResourceManager.GetString("PopupError_Comment_Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PopupError_Comment_Unknown {
            get {
                return ResourceManager.GetString("PopupError_Comment_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown error.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PopupError_Comment_UnknownError {
            get {
                return ResourceManager.GetString("PopupError_Comment_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown error.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PopupError_Title_Unknown {
            get {
                return ResourceManager.GetString("PopupError_Title_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to log out?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PopupInfo_Comment_Logout {
            get {
                return ResourceManager.GetString("PopupInfo_Comment_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm Log-out과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PopupInfo_Title_Logout {
            get {
                return ResourceManager.GetString("PopupInfo_Title_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Discharger Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PopupWaiting_Comment {
            get {
                return ResourceManager.GetString("PopupWaiting_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Processing discharge pause command.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PopupWaiting_Title_Pause {
            get {
                return ResourceManager.GetString("PopupWaiting_Title_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Processing discharge Resume command.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PopupWaiting_Title_Resume {
            get {
                return ResourceManager.GetString("PopupWaiting_Title_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Processing discharge start command.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PopupWaiting_Title_Start {
            get {
                return ResourceManager.GetString("PopupWaiting_Title_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Processing discharge Stop command.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PopupWaiting_Title_Stop {
            get {
                return ResourceManager.GetString("PopupWaiting_Title_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot close the program while discharging.Please stop the discharge first.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PopupWarning_Comment_CloseProgram {
            get {
                return ResourceManager.GetString("PopupWarning_Comment_CloseProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete this data?Once you confirm, this data will be permanetly deleted.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PopupWarning_Comment_Delete {
            get {
                return ResourceManager.GetString("PopupWarning_Comment_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to start discharge.Please try again or contact an administrator.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PopupWarning_Comment_FailStart {
            get {
                return ResourceManager.GetString("PopupWarning_Comment_FailStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You don&apos;t have permission to view device registration information. 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PopupWarning_Comment_NoPermissionDevice {
            get {
                return ResourceManager.GetString("PopupWarning_Comment_NoPermissionDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You don&apos;t have permission to view model registration information. 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PopupWarning_Comment_NoPermissionModel {
            get {
                return ResourceManager.GetString("PopupWarning_Comment_NoPermissionModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You don&apos;t have permission to view user registration information. 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PopupWarning_Comment_NoPermissionUser {
            get {
                return ResourceManager.GetString("PopupWarning_Comment_NoPermissionUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot proceed with this operation while discharging.\r\nPlease stop the discharge first.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PopupWarning_Comment_OpenPopup {
            get {
                return ResourceManager.GetString("PopupWarning_Comment_OpenPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PopupWarning_Title {
            get {
                return ResourceManager.GetString("PopupWarning_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Device과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PopupWarning_Title_DeleteDevice {
            get {
                return ResourceManager.GetString("PopupWarning_Title_DeleteDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Model과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PopupWarning_Title_DeleteModel {
            get {
                return ResourceManager.GetString("PopupWarning_Title_DeleteModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete User과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PopupWarning_Title_DeleteUser {
            get {
                return ResourceManager.GetString("PopupWarning_Title_DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No permission과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PopupWarning_Title_NoPermission {
            get {
                return ResourceManager.GetString("PopupWarning_Title_NoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pre-set Mode과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PreSetMode {
            get {
                return ResourceManager.GetString("PreSetMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Progress Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ProgressTime {
            get {
                return ResourceManager.GetString("ProgressTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reconnect과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Reconnect {
            get {
                return ResourceManager.GetString("Reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Re-enter New Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ReEnterNewPassword {
            get {
                return ResourceManager.GetString("ReEnterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Re-enter Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ReEnterPassword {
            get {
                return ResourceManager.GetString("ReEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Safety Condition과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SafetyCondition {
            get {
                return ResourceManager.GetString("SafetyCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Discharge Target과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SelectDischargeTarget {
            get {
                return ResourceManager.GetString("SelectDischargeTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Short Available과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ShortAvailable {
            get {
                return ResourceManager.GetString("ShortAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Simple Mode과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SimpleMode {
            get {
                return ResourceManager.GetString("SimpleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SoC (%)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Soc {
            get {
                return ResourceManager.GetString("Soc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SoC과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Soc_NoUnits {
            get {
                return ResourceManager.GetString("Soc_NoUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Discharge과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StartDischarge {
            get {
                return ResourceManager.GetString("StartDischarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Step 1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Step1 {
            get {
                return ResourceManager.GetString("Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Step 2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Step2 {
            get {
                return ResourceManager.GetString("Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Step Mode과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StepMode {
            get {
                return ResourceManager.GetString("StepMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target SoC (%)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TargetSoc {
            get {
                return ResourceManager.GetString("TargetSoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target Voltage (V)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TargetVoltage {
            get {
                return ResourceManager.GetString("TargetVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temp. (℃)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Temp {
            get {
                return ResourceManager.GetString("Temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temp.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Temp_NoUnits {
            get {
                return ResourceManager.GetString("Temp_NoUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temp Channel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TempChannel {
            get {
                return ResourceManager.GetString("TempChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temperature (℃)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TempMax (℃)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TempMax {
            get {
                return ResourceManager.GetString("TempMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TempMin (℃)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TempMin {
            get {
                return ResourceManager.GetString("TempMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temperature Module과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TempModule {
            get {
                return ResourceManager.GetString("TempModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UserSetting {
            get {
                return ResourceManager.GetString("UserSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Voltage (V)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Voltage {
            get {
                return ResourceManager.GetString("Voltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Voltage과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Voltage_NoUnits {
            get {
                return ResourceManager.GetString("Voltage_NoUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VoltMax (V)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string VoltMax {
            get {
                return ResourceManager.GetString("VoltMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VoltMin (V)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string VoltMin {
            get {
                return ResourceManager.GetString("VoltMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VoltSpec(V)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string VoltSpec {
            get {
                return ResourceManager.GetString("VoltSpec", resourceCulture);
            }
        }
    }
}
